### ISSUE TITLE
Unify and Restructure File System I/O

### ISSUE THREAD

**Issue by sincyn** [bpm-reborn/bpm.core#9]
# Unify and Restructure File System I/O

## Overview
Currently, our mod's schemas, workspaces, and world save data are scattered across various folders within the runtime installation directory. This issue aims to unify our file system I/O, creating a more organized and maintainable structure for all mod-related data.

## Objectives
1. Centralize all mod-related data in a single root folder
2. Create a consistent file I/O interface for accessing and managing mod data
3. Implement a configuration system for managing mod settings
4. Ensure backward compatibility with existing save data and schemas

### 1. File Structure Reorganization
- Create a single folder named "bpm" in the root of the installation directory
- Implement the following subfolder structure:
  ```
  bpm/
  ├── data/
  │   ├── world_data/
  │   └── workspace_data/
  ├── schemas/
  └── config/
  
  ```
- Move existing world save data from the "meng" folder to `bpm/data/world_data/`
- Transfer workspace data to `bpm/data/workspace_data/`
- Relocate all schema files to `bpm/schemas/`

### 2. File I/O Interface
- Develop a centralized file I/O interface to handle all read/write operations
- Implement methods for:
  - Reading/writing world save data
  - Accessing and updating schemas
  - Managing workspace files
  - Handling configuration files
- Ensure thread-safe operations for concurrent access

### 3. Configuration System
- Create a main configuration file: `bpm/config/config.yaml`
- Implement the following configuration options:
  ```yaml
  node_schema_git:
    repo: https://github.com/bpm-reborn/bpm.nodes.git
    tag: 0.1.0  # Optional, takes precedence over branch
    branch: main  # Optional, defaults to 'main' if neither tag nor branch is specified
  
  # Add placeholders for future configuration options
  gui_settings:
    # GUI-related settings to be implemented later
  
  performance:
    # Performance-related settings to be implemented later
  ```
- Develop a configuration manager to read, validate, and apply settings

### 4. Migration System
- Create a migration system to move existing data to the new structure
- Implement version checking to identify and migrate old data formats
- Provide detailed logging for the migration process

## Technical Considerations
- Use a consistent naming convention across all files and folders
- Implement error handling and logging for all file I/O operations
- Consider using a file locking mechanism for critical write operations
- Ensure cross-platform compatibility (Windows, macOS, Linux)

## Acceptance Criteria
- All mod-related data is successfully centralized in the "bpm" folder
- The file I/O interface correctly handles all read/write operations
- Configuration system is functional and correctly applies settings
- Existing save data and schemas are successfully migrated without loss of information
- Mod functions correctly with the new file structure and I/O system

## Subtasks
1. Implement new folder structure
2. Develop centralized file I/O interface
3. Create configuration system and manager
4. Implement data migration system
5. Update all existing code to use the new file I/O interface
6. Write unit tests for file I/O operations and configuration management
7. Create documentation for the new file system structure and usage

## Future Considerations
- Implement a backup system for critical data
- Develop a user interface for managing mod configurations
- Consider implementing a plugin system for extending file I/O capabilities

**Comment by sincyn** [comment]
- [x] All mod-related data is successfully centralized in the "bpm" folder
- [x] The file I/O interface correctly handles all read/write operations
- [x] Configuration system is functional and correctly applies settings
- [x] Existing save data and schemas are successfully migrated without loss of information
- [x] Mod functions correctly with the new file structure and I/O system

_Implemented in [**caf3639**](https://github.com/bpm-reborn/bpm.core/commit/caf36397c9aa72a21e2b19f6051d76db66c9f77c)_
